### ISSUE TITLE
Order could include different products with their own quantity

### ISSUE THREAD

**Issue by CyrusKrasnikov** [VeronikaPl/Electronic_auction_software#3]
@VelikoivanenkoNikita would you like to add a new class OrderProduct to the [AuctionDataClasses.dbml](Electonic_auctionWPF/AuctionDataLib/AuctionDataClasses.dbml) like here:
!['Example table'](https://learn.microsoft.com/en-us/aspnet/web-api/overview/older-versions/using-web-api-1-with-entity-framework-5/using-web-api-with-entity-framework-part-2/_static/image2.png)

So buyer could order multiple products at once

**Comment by AnnaZubritskaya** [comment]
Hello, @CyrusKrasnikov ! Im the one who was responsible for creating a Database and we came to a decision that the whole concept of a database is not possible for us. We need a cloud server (which is not free) or only one user will have a database installed on his computer and thats very uncomfortable, because all of us need it. So we decided to create simple classes like User, Product and Order. Later in the code we will be using lists for storing information. If you have any other suggestions how to resolve our issue or to improve the existing solution, we are looking forward to your response!

**Comment by CyrusKrasnikov** [comment]
> Hello, @CyrusKrasnikov ! Im the one who was responsible for creating a Database and we came to a decision that the whole concept of a database is not possible for us. We need a cloud server (which is not free) or only one user will have a database installed on his computer and thats very uncomfortable, because all of us need it. So we decided to create simple classes like User, Product and Order. Later in the code we will be using lists for storing information. If you have any other suggestions how to resolve our issue or to improve the existing solution, we are looking forward to your response!

Hello @AnnaZubritskaya! Thank you for your quick response. That was a great idea to develop electonic auction app even for local computer. I easily cloned the project, run it and the app automatically created database. Cool! I`ve got a new enhancement for you #4
